config/routes.rb
Taskie::Application.routes.draw do
  concern :commentable do
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: :show
    resources :projects, only: [:index, :show] do
      resources :milestones, only: [:index, :show]
      resources :tasks, only: [:index, :show]
    end
  end

  devise_for :users, skip: [:registrations]
  as :user do
    controller "devise/registrations" do
      get 'users/edit', action: :edit, as: 'edit_user_registration'
      patch 'users', action: :update, as: 'user_registration'
    end
  end

  resources :projects, except: :index do
    resources :milestones
    resources :tasks, concerns: :commentable do
      get :follow, on: :member
    end
  end

  resource :settings, only: [:show, :update]

  controller :pages do
    root action: :dashboard
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user

  validates :task, :user, :text, presence: true

  before_update :modifiable?
  before_destroy :modifiable?
  after_create :notify_followers

  default_scope -> { order :created_at }

  def modifiable?
    created_at > 1.day.ago
  end

  private

  def notify_followers
    task.followers.where.not("id = ?", user.id).each do |follower|
      TaskMailer.new_comment(self, follower).deliver_now
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_task
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def show
  end

  def create
    @comment = @task.comments.new(comment_params.merge(user_id: current_user.id))

    if @comment.save
      redirect_to project_task_path(id: @task), notice: 'Comment was successfully posted.'
    else
      redirect_to project_task_path(id: @task), alert: "Don't submit empty comments!"
    end
  end

  def edit
    respond_to :js
  end

  def update
    @success = @comment.update(comment_params)
    respond_to :js
  end

  def destroy
    if @comment.destroy
      redirect_to project_task_path(id: @task), notice: 'Comment was successfully deleted.'
    else
      redirect_to project_task_path(id: @task), alert: t('access.denied')
    end
  end

  private

  def set_task
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:task_id])
  end

  def set_comment
    @comment ||= @task.comments.where(user_id: current_user.id).find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def span_with_tooltip(text, tooltip)
    content_tag :span, text, class: "has-tooltip", data: { title: tooltip }
  end

  def time_distance_with_tooltip(time)
    span_with_tooltip distance_of_time_in_words_to_now(time), time.to_s(:long)
  end
end

app/views/comments/_comment.html.haml
= content_tag :blockquote, class: "comment", id: "comment#{comment.id}" do
  %small
    :erb
      <%= user_with_gravatar comment.user %> wrote <%= time_distance_with_tooltip comment.created_at %> ago <% if comment.updated_at > comment.created_at %><em>(last edited <%= time_distance_with_tooltip(comment.updated_at) %> ago)</em><% end %><span class="links"> [ <%= link_to "#", "#comment#{comment.id}", name: "comment#{comment.id}" %><% if comment.user == current_user and comment.modifiable? %> | <%= link_to "edit", edit_project_task_comment_path(@project, @task, comment), remote: true %> | <%= link_to "delete", project_task_comment_path(@project, @task, comment), data: { method: :delete, confirm: t("confirm.prompt") } %><% end %> ]</span>
  %div= render_markdown(comment.text)

app/views/comments/_form.html.haml
= content_tag :blockquote, class: "blockquote-white comment", id: ("comment#{@comment.id}" unless @comment.new_record?) do
  = form_for [@project, @task, @comment], remote: !@comment.new_record? do |f|
    %small
      :erb
        <%= user_with_gravatar current_user %><% unless @comment.new_record? %> is editing his comment (<%= link_to "cancel", project_task_comment_path(@project, @task, @comment), remote: true %>)<% end %>
    .form-group= f.text_area :text, placeholder: "Comment", rows: 5, class: "form-control"
    .form-group= f.submit "Post", class: "btn btn-primary"

app/views/comments/edit.js.erb
$("blockquote#comment<%= @comment.id %>").replaceWith("<%= escape_javascript render partial: 'form' %>")

app/views/comments/show.js.erb
$("blockquote#comment<%= @comment.id %>").replaceWith("<%= escape_javascript render @comment %>")

app/views/comments/update.js.erb
$("form.edit_comment").parents("blockquote.comment").replaceWith("<%= escape_javascript render partial: 'comment', locals: { comment: @comment } %>")