config/routes.rb
Taskie::Application.routes.draw do
  concern :commentable do
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: :show
    resources :projects, only: [:index, :show] do
      resources :milestones, only: [:index, :show]
      resources :tasks, only: [:index, :show]
    end
  end

  devise_for :users, skip: [:registrations]
  as :user do
    controller "devise/registrations" do
      get 'users/edit', action: :edit, as: 'edit_user_registration'
      patch 'users', action: :update, as: 'user_registration'
    end
  end

  resources :projects, except: :index do
    resources :milestones
    resources :tasks, concerns: :commentable do
      get :follow, on: :member
    end
  end

  resource :settings, only: [:show, :update]

  controller :pages do
    root action: :dashboard
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include PublicActivity::Common

  enum status: [:active, :completed], priority: { low: 1, normal: 2, high: 3, critical: 4 }

  belongs_to :assignee, class_name: "User"
  belongs_to :creator, class_name: "User"
  belongs_to :project
  belongs_to :milestone
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :followers, class_name: "User"

  validates :name, :project, :creator, presence: true

  after_create :set_followers
  after_save :notify_assignee, if: -> { assignee_id_changed? && assignee_id.present? && assignee_id != creator_id }

  scope :sorted, -> { order :status, priority: :desc, updated_at: :desc }

  def name_with_id
    "##{id} #{name}"
  end

  def add_follower(user)
    followers << user if !follower_ids.include?(user.id) && user.auto_follow_tasks
  end

  private

  def set_followers
    add_follower creator
  end

  def notify_assignee
    add_follower assignee
    TaskMailer.task_assigned(self).deliver_now
  end
end

app/controllers/api/tasks_controller.rb
module Api
  class TasksController < Api::BaseController
    before_action :set_tasks
    before_action :set_task, only: :show

    def index
      render json: @tasks
    end

    def show
      render json: @task
    end

    private

    def set_tasks
      @project = current_user.projects.find_by_id(params[:project_id])
      @tasks = @project&.tasks
    end

    def set_task
      @task = @tasks&.find_by(id: params[:id])
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_associations, only: [:new, :edit]
  before_action :set_task, only: [:show, :edit, :follow, :update, :destroy]
  layout "projects_nested", only: :index

  def index
    tasks =
      @project
      .tasks
      .includes(:comments, :creator, :assignee, :milestone)
      .sorted
      .page(params[:page])

    @tasks =
      if current_user.tasks_per_page > 0
        tasks.per(current_user.tasks_per_page)
      else
        tasks
      end
  end

  def show
    @comments = @task.comments.includes(:user)
    @comment = @comments.new
  end

  def new
    @task = @project.tasks.new
  end

  def edit
  end

  def follow
    if @task.follower_ids.include? current_user.id
      @task.followers.delete current_user
    else
      @task.add_follower(current_user)
    end
    redirect_to project_task_path
  end

  def create
    @task = @project.tasks.new(task_params.merge(creator: current_user))

    if @task.save
      redirect_to project_task_path(id: @task), notice: 'Task was successfully created.'
    else
      set_associations
      render action: 'new'
    end
  end

  def update
    if params[:task][:status].present?
      if @task.update(task_params)
        @task.create_activity :update, owner: current_user, parameters: { type: "status", changes: @task.status }
      end
    elsif @task.update(task_params)
      @task.create_activity(
        :update,
        owner: current_user,
        parameters: {
          type: 'full',
          changes: @task.previous_changes.reject { |k| k == 'updated_at' }
        }
      )
      redirect_to project_task_path(id: @task), notice: 'Task was successfully updated.'
    else
      set_associations
      render action: 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
  end

  private

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def set_associations
    @users = @project.users.pluck(:username, :id)
    @milestones = @project.milestones.pluck(:title, :id)
  end

  def task_params
    permitted =
      if params[:task][:status].present?
        [:status]
      else
        [:assignee_id, :name, :details, :priority, :milestone_id]
      end

    params.require(:task).permit(permitted)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def status_label_for(task_or_status)
    if task_or_status.try(:completed?) || task_or_status.in?(["completed", 1])
      content_tag :span, "Completed", class: "label label-success"
    else
      content_tag :span, "Active", class: "label label-primary"
    end
  end

  def check_box_with_status_for(task)
    form_for(
      task,
      url: project_task_path(project_id: task.project_id, id: task),
      remote: true,
      html: { class: 'form-inline status-toggle' }
    ) do |f|
      f.check_box(:status, {}, 'completed', 'active') + status_label_for(task)
    end
  end

  def tasks_filter_select
    content_tag :div, class: "btn-group" do
      task_scopes_for_filter.map do |scope|
        link_to scope.titleize, project_tasks_path(filter: scope, page: params[:page]), class: 'btn btn-sm btn-default'
      end.join.html_safe
    end
  end

  def task_scopes_for_filter
    %w(all active completed)
  end

  def priority_badge(task_or_priority)
    priority =
      case task_or_priority
      when Integer
        Task.priorities.invert[task_or_priority]
      when Task
        task_or_priority.priority
      else
        task_or_priority
      end
    content_tag :span, priority, class: "badge #{priority_to_class(priority)}"
  end

  def priority_to_class(n)
    "badge-" + HashWithIndifferentAccess.new(low: "blue", normal: "green", high: "orange", critical: "red")[n]
  end
end

app/views/tasks/_form.html.haml
.col-sm-5
  = form_for [@project, @task] do |f|
    .form-group= f.text_field :name, class: "form-control", placeholder: "Name"
    .form-group= f.text_area :details, class: "form-control", placeholder: "Details", rows: 5
    .form-group
      = f.label :milestone_id, "Milestone"
      = f.select :milestone_id, options_for_select(@milestones, @task.milestone_id), { include_blank: true }, class: "form-control"
    .form-group
      = f.label :priority
      = f.select :priority, options_for_select(Task.priorities.keys, @task.priority), { include_blank: false }, class: "form-control"
    .form-group
      = f.label :assignee_id, "Assign to"
      = f.select :assignee_id, options_for_select(@users, @task.assignee_id), { include_blank: true }, class: "form-control"
    .form-group= f.submit class: "btn btn-primary btn-block"

app/views/tasks/_task.html.haml
= cache [task, task.milestone, hide_assignee ||= false, hide_milestone ||= false] do
  = content_tag :li, class: "list-group-item clearfix task-details #{task.status}-task" do
    = priority_badge task
    %h4.list-group-item-heading
      = link_to task.name, project_task_path(task.project_id, task.id)
      - if (@comments_size = task.comments.size) > 0
        %small
          %i.fa.fa-comments
          = pluralize @comments_size, "comment"
    .pull-left
      - if !hide_milestone and task.milestone.present?
        %div
          %i.fa.fa-calendar
          = link_to task.milestone.title, project_milestone_path(task.project_id, task.milestone)
      %div= check_box_with_status_for task
    .pull-right
      :erb
        created <%= time_distance_with_tooltip task.created_at %> ago by <%= user_with_gravatar task.creator %><% unless hide_assignee %>, assigned to <%= user_with_gravatar task.assignee %><% end %>

app/views/tasks/edit.html.haml
- title "Edit task"

%h2
  Edit task
  %small= link_to @task.project.name, @task.project

= render "form"

app/views/tasks/index.html.haml
- title "#{@project.name}: Tasks", add: { page: params[:page] }, action: :clear

%p= link_to "New task", new_project_task_path, class: "btn btn-info"

- if @tasks.any?
  %ul.list-group= render @tasks
  = paginate @tasks
- else
  %h2 No tasks here

app/views/tasks/new.html.haml
- title "New task"

%h2
  New task
  %small= link_to @task.project.name, @task.project

= render "form"

app/views/tasks/show.html.haml
- title "#{@project.name} / #{@task.name}", action: :clear

.row
  .panel.panel-default.task-info
    .panel-heading.clearfix
      .pull-right.btn-group
        = link_to follow_project_task_path, class: "btn btn-xs btn-info" do
          - if @task.followers.include?(current_user)
            %i.fa.fa-star
            Unfollow
          - else
            %i.fa.fa-star-o
            Follow
        = link_to edit_project_task_path(id: @task), class: "btn btn-xs btn-primary" do
          %i.fa.fa-edit
          Edit
        = link_to project_task_path(id: @task), class: "btn btn-xs btn-danger", data: { method: :delete, confirm: t("confirm.prompt") } do
          %i.fa.fa-trash-o
          Delete
      %div
        %h4= @task.name
    .panel-body.clearfix
      .pull-left
        %div
          %i.fa.fa-folder
          = link_to @project.name, @project
        - if @task.milestone.present?
          %div
            %i.fa.fa-calendar
            = link_to @task.milestone.title, project_milestone_path(@task.project, @task.milestone)
        %div= check_box_with_status_for @task
      .pull-right.text-right
        %div= priority_badge @task
        %div
          assigned to
          = user_with_gravatar @task.assignee

%blockquote.blockquote-primary.task-details
  %small
    = user_with_gravatar @task.creator
    created
    = time_distance_with_tooltip @task.created_at
    ago
  %div
    - if @task.details.present?
      = render_markdown @task.details
    - else
      %p.text-muted No details

- (@comments + @task.activities.includes(:owner)).sort{ |x,y| x[:created_at] <=> y[:created_at] }.each do |activity|
  - if activity.is_a?(PublicActivity::Activity)
    = render_activity activity
  - else
    = render activity

= render "comments/form"

= javascript_include_tag "taskie.diff-explain.toggle"

app/views/tasks/update.js.erb
$('form#edit_task_<%= @task.id %>').replaceWith('<%= escape_javascript(check_box_with_status_for(@task)) %>');
$("#spinner").hide("fast");