config/routes.rb
Taskie::Application.routes.draw do
  concern :commentable do
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: :show
    resources :projects, only: [:index, :show] do
      resources :milestones, only: [:index, :show]
      resources :tasks, only: [:index, :show]
    end
  end

  devise_for :users, skip: [:registrations]
  as :user do
    controller "devise/registrations" do
      get 'users/edit', action: :edit, as: 'edit_user_registration'
      patch 'users', action: :update, as: 'user_registration'
    end
  end

  resources :projects, except: :index do
    resources :milestones
    resources :tasks, concerns: :commentable do
      get :follow, on: :member
    end
  end

  resource :settings, only: [:show, :update]

  controller :pages do
    root action: :dashboard
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :restrict_with_exception
  has_many :milestones, dependent: :restrict_with_exception
  belongs_to :owner, class_name: "User"
  has_and_belongs_to_many :users

  validates :name, :owner, presence: true

  after_save :add_owner_to_participants

  private

  def add_owner_to_participants
    users << owner
  end
end

app/controllers/api/projects_controller.rb
module Api
  class ProjectsController < Api::BaseController
    before_action :set_projects
    before_action :set_project, only: :show

    def index
      render json: @projects
    end

    def show
      render json: @project
    end

    private

    def set_projects
      @projects = current_user.projects.includes(:owner, :users, :milestones)
    end

    def set_project
      @project = @projects.find_by_id(params[:id])
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  before_action :set_new_project, only: :new
  before_action :set_users, only: [:new, :edit]

  def show
    redirect_to project_tasks_path(params[:id])
  end

  def new
  end

  def edit
  end

  def create
    @project = current_user.owned_projects.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path, notice: 'Project was successfully destroyed.'
  end

  private

  def set_new_project
    @project = current_user.owned_projects.new
  end

  def set_users
    @users = User.active.where("id != ?", @project.owner_id).pluck(:username, :id)
  end

  def set_project
    @project = current_user.owned_projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :details, user_ids: [])
  end
end

app/views/projects/_form.html.haml
.col-sm-5
  = form_for @project do |f|
    .form-group= f.text_field :name, class: "form-control", placeholder: "Name"
    .form-group= f.text_area :details, class: "form-control", placeholder: "Details", rows: 5
    .form_group= f.label "Owner"
    .form-group= user_with_gravatar @project.owner
    .form-group= f.label :user_ids, "Participants"
    .form-group= select :project, :user_ids, options_for_select(@users, @project.user_ids), { include_blank: true }, multiple: true, class: "form-control"
    .form-group= f.submit class: "btn btn-primary btn-block"

:coffeescript
  $("#project_user_ids").select2()

app/views/projects/_project.html.haml
%h1= @project.name
%p
  Owner:
  = user_with_gravatar(@project.owner)
- if @project.details.present?
  %hr
  %div= render_markdown(@project.details)
%hr
  .btn-group
    - if current_user == @project.owner
      = link_to "Edit", edit_project_path(@project), class: "btn btn-primary"
      - unless @project.tasks.any?
        = link_to "Delete", project_path(@project), data: { method: :delete, confirm: t("confirm.prompt") }, class: "btn btn-danger"

app/views/projects/edit.html.haml
- title "Edit project"

%h2 Edit project

= render "form"

app/views/projects/new.html.haml
- title "New project"

%h2 New project

= render "form"