config/routes.rb
Taskie::Application.routes.draw do
  concern :commentable do
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: :show
    resources :projects, only: [:index, :show] do
      resources :milestones, only: [:index, :show]
      resources :tasks, only: [:index, :show]
    end
  end

  devise_for :users, skip: [:registrations]
  as :user do
    controller "devise/registrations" do
      get 'users/edit', action: :edit, as: 'edit_user_registration'
      patch 'users', action: :update, as: 'user_registration'
    end
  end

  resources :projects, except: :index do
    resources :milestones
    resources :tasks, concerns: :commentable do
      get :follow, on: :member
    end
  end

  resource :settings, only: [:show, :update]

  controller :pages do
    root action: :dashboard
  end
end

app/views/layouts/_footer.html.haml
.container
  Taskie revision
  = link_to REVISION[0..8], "https://github.com/hauptstimme/taskie/commit/#{REVISION}"
  .pull-right#links
    = link_to "https://github.com/Hauptstimme/taskie", target: "_blank" do
      %i.fa.fa-github.fa-2x
    = link_to "https://hauptstimme.github.io/projects", target: "_blank" do
      %i.hauptstimme-icon.hauptstimme-icon-main.hauptstimme-large

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{http: {equiv: "X-UA-Compatible"}, content: "IE=Edge,chrome=1"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : "Taskie"
    = csrf_meta_tags
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    -# ["144x144", "114x114", "72x72", nil].each do |size|
      =# favicon_link_tag ["apple-touch-icon", size, "precomposed.png"].compact.join("-"), rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: size
    = favicon_link_tag '//hauptstimme.tk/favicon.ico', rel: 'shortcut icon'

    = stylesheet_link_tag "application", media: "all"
    = stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Roboto:300", media: 'all'
    = javascript_include_tag "application"
    = cdn_css_tag "font-awesome/4.0.3/css/font-awesome.min"

  %body
    .navbar.navbar-inverse
      .container
        .navbar-header
          = link_to root_path, class: "navbar-brand" do
            Taskie
            %div#spinner
          %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: "#navbar-main"}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        .navbar-collapse.collapse#navbar-main
          - if current_project_id = Rails.application.routes.recognize_path(request.path)[:project_id]
            %ul.nav.navbar-nav.navbar-left
              %li
                = link_to project_path(current_project_id) do
                  %i.fa.fa-folder
                  = Project.find(current_project_id).name
          %ul.nav.navbar-nav.navbar-right
            - if signed_in?
              %li.dropdown
                = link_to nil, data: { toggle: "dropdown", target: "#" }, class: "dropdown-toggle" do
                  %i.fa.fa-suitcase.fa-fw
                  Projects
                  %i.fa.fa-caret-down
                %ul.dropdown-menu
                  - cache ["current_user_projects", current_user.projects] do
                    - if current_user.projects.any?
                      - current_user.projects.each do |p|
                        %li
                          = link_to p do
                            %i.fa.fa-folder.fa-fw
                            = p.name
                      %li.divider
                  %li
                    = link_to new_project_path do
                      %i.fa.fa-plus.fa-fw
                      New project
              %li.dropdown
                = link_to nil, data: { toggle: "dropdown", target: "#" }, class: "dropdown-toggle" do
                  %i.fa.fa-user.fa-fw
                  Account
                  %i.fa.fa-caret-down
                %ul.dropdown-menu
                  %li.dropdown-header= user_with_gravatar current_user
                  %li.divider
                  %li
                    = link_to new_user_invitation_path do
                      %i.fa.fa-plus.fa-fw
                      Invite
                  %li
                    = link_to settings_path do
                      %i.fa.fa-cog.fa-fw
                      Settings
                  %li
                    = link_to destroy_user_session_path do
                      %i.fa.fa-sign-out.fa-fw
                      Logout
            - else
              %li
                = link_to new_user_session_path do
                  %i.fa.fa-sign-in.fa-fw
                  Login

    .container#main-content
      = bootstrap_flash
      = yield

    %footer
      .container
        Taskie
        - if REVISION.present?
          revision
          = link_to REVISION[0,9], "https://github.com/hauptstimme/taskie/commit/#{REVISION}"
        .pull-right#links
          = link_to "http://github.com/hauptstimme/taskie", target: "_blank" do
            %i.fa.fa-github.fa-2x

app/views/layouts/projects_nested.html.haml
= inside_layout "application" do
  .row
    .col-md-3.project-details= render @project
    .col-md-9
      %ul.nav.nav-tabs
        = menu_item "Tasks", project_tasks_path
        = menu_item "Milestones", project_milestones_path
      = yield